export type DomainId = 'hardware'|'os'|'network'|'programming'|'data'|'web'|'cloud'|'ai';
export type KnowledgeNode = {
  id:string; domain:DomainId; title:string; en:string; depth:string; summary:string; analogy:string;
  why:string; mechanism:string[]; aiUse:string; debug:string; terms:[string,string][]; connects:string[];
};
export type Domain = { id:DomainId; title:string; en:string; icon:string; thesis:string };

export const domains:Domain[] = [
  {id:'hardware',title:'硬件与计算',en:'Hardware & Computation',icon:'▣',thesis:'所有软件最终都要落到电路、指令、内存与数据搬运。'},
  {id:'os',title:'操作系统',en:'Operating Systems',icon:'⌘',thesis:'把有限硬件伪装成“每个程序都有自己电脑”的资源管理层。'},
  {id:'network',title:'网络与互联网',en:'Networking',icon:'↗',thesis:'让不可靠、跨设备的传输，组合成看起来可靠的服务。'},
  {id:'programming',title:'编程与软件结构',en:'Programming',icon:'{}',thesis:'把状态、规则与变化组织成可验证、可修改的程序。'},
  {id:'data',title:'数据与数据库',en:'Data & Databases',icon:'▥',thesis:'把现实世界压缩成结构，并在正确性、速度与成本之间取舍。'},
  {id:'web',title:'Web 与应用',en:'Web & Apps',icon:'◇',thesis:'把浏览器、服务器、数据和身份系统组合成用户能操作的产品。'},
  {id:'cloud',title:'云、部署与可靠性',en:'Cloud & Reliability',icon:'☁',thesis:'让“我电脑能跑”变成“别人随时能稳定访问”。'},
  {id:'ai',title:'AI 与大模型',en:'AI & LLMs',icon:'✦',thesis:'模型不是魔法层，而是数据、计算、概率与软件系统的叠加。'}
];

export const nodes:KnowledgeNode[] = [
  {id:'bits-bytes',domain:'hardware',title:'比特、字节与编码',en:'Bits, Bytes & Encoding',depth:'地基层',summary:'计算机内部没有“文字、图片、金币、血量”，只有被解释成不同含义的比特序列。',analogy:'像同一串摩斯密码：规则不同，解读出的含义也不同。文件格式、本质上就是“大家约定怎么解释这些字节”。',why:'数字电路最容易稳定区分两种状态，因此二进制成为底层表示；更高层再用编码规则把数字映射成字符、颜色、声音和指令。',mechanism:['1 个 bit 只能表示 0/1，两种状态','8 个 bit 组成 1 byte，可表示 256 种组合','UTF-8、PNG、MP3 都是在规定“这些 byte 应该怎样解释”','程序读取错误格式时，数据没变，解释方式变了，于是出现乱码或损坏'],aiUse:'理解 Token、图片上传、Base64、文件大小、模型上下文时都要用到“数据最终是字节”的意识。',debug:'遇到乱码、文件打不开、接口返回奇怪字符，先问：编码是什么？字节有没有被截断？发送端和接收端是否用同一种解释规则？',terms:[['bit','最小二进制单位，只能是 0 或 1'],['byte','通常由 8 个 bit 组成的数据单位'],['UTF-8','把 Unicode 字符编码成字节的主流规则'],['编码','把一种信息映射成另一种可存储形式的规则']],connects:['cpu','memory','data-model','tokens-embeddings']},
  {id:'cpu',domain:'hardware',title:'CPU、指令与时钟',en:'CPU & Instructions',depth:'机器层',summary:'CPU 不理解“登录”“敌人 AI”“保存文件”，它只不断取出极简单的机器指令并执行。',analogy:'像一个速度极快但只会几十/几百种动作的工人：搬数、加减、比较、跳转。复杂软件只是海量简单动作的编排。',why:'把复杂任务拆成稳定、可复用的基本指令，硬件就能用统一机制执行任意程序。',mechanism:['Fetch：从内存取下一条指令','Decode：判断这是加法、移动、跳转还是别的操作','Execute：ALU/执行单元完成动作','Write back：结果写回寄存器或内存','Program Counter 决定下一条指令位置，条件跳转形成 if/loop'],aiUse:'AI 写出的 Python/JS 最终也会经解释器、JIT 或编译器转成 CPU 能执行的底层操作。性能问题常常是“做了太多指令”或“等数据太久”。',debug:'卡顿不一定是 CPU 慢；可能在等磁盘、网络、GPU。先区分 CPU-bound 与 I/O-bound。',terms:[['instruction','CPU 能直接执行的机器动作'],['register','CPU 内部极快、极少量的存储位置'],['clock','驱动处理器状态更新的节拍'],['ISA','软件与 CPU 之间约定的指令集合']],connects:['bits-bytes','memory','process-thread','runtime-errors']},
  {id:'memory',domain:'hardware',title:'内存、地址与缓存层级',en:'Memory & Caches',depth:'机器层',summary:'程序看到的是地址空间；真正的数据可能在寄存器、CPU Cache、RAM、SSD 之间移动。越近 CPU 越快，也越贵、越小。',analogy:'桌面、抽屉、书柜、仓库：离手越近越快，但容量越小。',why:'处理器速度远高于大容量存储，必须用多级缓存减少“CPU 等数据”的时间。',mechanism:['程序通过地址定位数据','CPU 先查 L1/L2/L3 Cache，再访问 RAM','RAM 不够时 OS 可能把冷数据换到磁盘','顺序访问通常比随机访问更容易利用缓存'],aiUse:'浏览器爆内存、Node 进程 OOM、模型显存不足，都是“工作集超出某层容量”的具体表现。',debug:'内存泄漏看“占用持续增长且不释放”；显存不足看模型参数、KV Cache、batch；性能差还要看是否频繁 cache miss。',terms:[['address','数据在地址空间中的位置编号'],['cache','保存近期/附近数据的高速小容量存储'],['RAM','程序运行时主要使用的易失性内存'],['OOM','Out Of Memory，无法再分配所需内存']],connects:['cpu','virtual-memory','gpu','cache']},
  {id:'gpu',domain:'hardware',title:'GPU 与并行计算',en:'GPU & Parallelism',depth:'机器层',summary:'GPU 用大量相对简单的计算单元同时处理相似运算，特别适合矩阵、图形和神经网络。',analogy:'CPU 像少量全能工程师；GPU 像成千上万个擅长同一类流水线工作的工人。',why:'图形渲染天然要求对大量像素/顶点做相似运算，后来同类并行能力被机器学习大量利用。',mechanism:['数据被分批送到 GPU 显存','大量线程执行相似 kernel','矩阵乘法把神经网络的大量加权求和并行化','CPU 与 GPU 之间搬数据也有成本'],aiUse:'本地跑模型时“模型多大、量化多少、上下文多长”最终都会落到显存与算力预算。',debug:'GPU 利用率低可能不是 GPU 不够快，而是 CPU、数据加载或频繁传输成了瓶颈。',terms:[['VRAM','GPU 专用显存'],['kernel','在 GPU 上并行执行的计算函数'],['tensor','多维数字数组，深度学习的核心数据结构'],['quantization','用更低精度表示参数以降低内存/计算成本']],connects:['cpu','memory','inference-training','transformer']},
  {id:'process-thread',domain:'os',title:'进程、线程与调度',en:'Processes & Threads',depth:'系统层',summary:'进程是操作系统给“正在运行的程序”包装出的隔离环境；线程是进程内部可被调度的执行流。',analogy:'进程像独立办公室，线程像办公室里的员工；共享办公室资源，但员工可以同时处理不同任务。',why:'多个程序需要同时运行又不能随便踩坏彼此内存，OS 通过隔离与调度制造“大家都在同时运行”的效果。',mechanism:['每个进程拥有自己的虚拟地址空间和资源表','线程共享进程内的大部分内存','调度器在可运行线程之间切换 CPU 时间片','切换需要保存/恢复上下文，因此并发不是免费'],aiUse:'后端并发、游戏主线程卡顿、浏览器 Worker、Python 多进程都建立在这层概念上。',debug:'先问问题是“单线程阻塞”“锁竞争”“进程崩溃”还是“CPU 被打满”，不要统称为卡。',terms:[['process','拥有独立资源边界的运行中程序实例'],['thread','进程内的一条执行流'],['scheduler','决定谁何时获得 CPU 的系统组件'],['context switch','CPU 从一个执行流切换到另一个时保存/恢复状态']],connects:['cpu','virtual-memory','runtime-errors','server-linux']},
  {id:'virtual-memory',domain:'os',title:'虚拟内存与分页',en:'Virtual Memory',depth:'系统层',summary:'程序以为自己拥有一片连续、私有的大内存；操作系统和硬件把虚拟地址翻译到真实物理页。',analogy:'酒店房间号不是建筑施工时的砖块坐标。房间号提供稳定抽象，后台可以重新安排实际位置。',why:'隔离程序、简化编程、允许内存按页灵活分配，并让一部分冷数据暂时换出。',mechanism:['CPU 产生虚拟地址','MMU 根据页表翻译成物理地址','TLB 缓存近期地址翻译','缺页时 OS 介入加载/分配页面','非法访问触发保护异常'],aiUse:'理解“为什么一个进程看不到另一个进程变量”“为什么地址不是物理 RAM 位置”“为什么内存不足会突然变慢”。',debug:'Segmentation fault/Access violation 往往是访问了无效或无权限地址；swap 过多会导致系统明显抖动。',terms:[['page','虚拟内存管理的固定大小块'],['page table','虚拟页到物理页的映射表'],['TLB','缓存地址翻译结果的高速硬件结构'],['page fault','访问页面需要 OS 介入处理的事件']],connects:['memory','process-thread','filesystem','permissions']},
  {id:'filesystem',domain:'os',title:'文件系统与路径',en:'Filesystems & Paths',depth:'系统层',summary:'文件系统把块设备上的原始字节组织成“文件、目录、名称、权限、元数据”这种人类可管理结构。',analogy:'硬盘像没有标签的巨大仓库；文件系统负责货架编号、目录索引、所有权和空间回收。',why:'程序需要稳定地按名字保存长期数据，而不是记住“第 8,291,904 个扇区”。',mechanism:['路径被逐级解析成目录项','目录项指向文件元数据与数据块','写入可能先进入缓存再落盘','日志/journaling 用于崩溃后恢复一致性'],aiUse:'AI 编程最常见的新手错误之一就是路径、工作目录、文件是否真的存在，以及大小写/权限差异。',debug:'遇到 ENOENT 先打印当前工作目录与实际路径；遇到写入失败再看权限、磁盘空间、锁与只读文件系统。',terms:[['path','定位文件或目录的名称链'],['working directory','相对路径解析时的当前目录'],['metadata','文件大小、时间、权限等附加信息'],['journaling','先记录待做变更以帮助崩溃恢复一致性']],connects:['permissions','server-linux','deployment-ci']},
  {id:'permissions',domain:'os',title:'权限、用户与隔离',en:'Permissions & Isolation',depth:'安全层',summary:'系统不会默认信任所有程序。用户身份、权限位、沙箱和能力边界决定“谁能读、写、执行什么”。',analogy:'办公楼的门禁：你拿到的是某些门的钥匙，而不是整栋楼的万能钥匙。',why:'一旦任何程序都能随意读取所有文件、控制其他进程或监听网络，系统就无法承载多个用户和不可信软件。',mechanism:['进程带着某个用户/身份运行','访问资源时内核检查权限','更高权限操作需要显式授权','容器/沙箱进一步缩小可见资源范围'],aiUse:'部署报 Permission denied、API Key 泄露、前后端权限边界、最小权限原则都在这一层。',debug:'不要用“全部 777 / 管理员运行”掩盖问题；先确认哪个主体需要哪一种最小权限。',terms:[['user/group','系统用来归属权限的身份单位'],['least privilege','只授予完成任务所需的最低权限'],['sandbox','限制程序可访问资源的隔离环境'],['root/admin','拥有系统级高权限的身份']],connects:['filesystem','auth-security','container','server-linux']},
  {id:'ip-routing',domain:'network',title:'IP、路由与分组',en:'IP & Routing',depth:'网络层',summary:'互联网不把“整个文件”一次送过去，而是拆成分组；路由器只负责把每个分组朝目的地下一跳转发。',analogy:'像全球快递网络：包裹带目的地址，中转站只决定下一站，不需要知道包裹内容。',why:'分组交换让大量用户共享网络，并允许中间某条路径故障时绕路。',mechanism:['应用数据被封装进更低层协议数据','IP 包包含源/目标地址','每个路由器查路由表选择下一跳','不同包可能经过不同路径，IP 本身不保证到达顺序或可靠性'],aiUse:'“服务器在哪”“为什么延迟高”“公网/内网是什么”“云服务为什么需要 region”都从 IP 和路由开始。',debug:'先区分 DNS 失败、无法路由、端口不通、应用返回错误；ping/traceroute 只能回答网络的一部分问题。',terms:[['IP address','网络层用来标识接口位置的地址'],['packet','网络传输中的分组数据单元'],['router','在不同网络之间转发 IP 包的设备/程序'],['latency','数据往返或单程传输所需时间']],connects:['dns','tcp-udp','http-tls','server-linux']},
  {id:'dns',domain:'network',title:'DNS：名字如何找到机器',en:'DNS',depth:'网络层',summary:'DNS 是分层、分布式的命名系统，把人类记得住的域名解析成网络可用的地址等记录。',analogy:'不是一本全球电话簿，而是一套“问本地→问上级→问权威负责人”的分级查询体系。',why:'服务器地址会变化，人类也不想记 IP，因此名称与位置需要解耦。',mechanism:['浏览器/系统先查本地缓存','递归解析器代你向 DNS 层级查询','权威 DNS 返回域名记录','结果按 TTL 缓存，因此改 DNS 不会全球瞬间生效'],aiUse:'部署网站、配置自定义域名、CDN、邮件、API 子域名时都会直接碰 DNS。',debug:'“域名打不开但 IP 能访问”优先查 DNS；改记录后仍旧旧值，查 TTL 与不同递归解析器缓存。',terms:[['A/AAAA','域名到 IPv4/IPv6 地址的记录'],['CNAME','把一个名称指向另一个名称的别名记录'],['TTL','DNS 记录允许缓存的时间'],['resolver','替客户端递归查询 DNS 的服务']],connects:['ip-routing','http-tls','deployment-ci','cache']},
  {id:'tcp-udp',domain:'network',title:'TCP、UDP 与可靠性',en:'TCP & UDP',depth:'传输层',summary:'IP 只负责尽力送包；TCP 在其上增加连接、顺序、重传、流量控制。UDP 则保持更轻量，让应用自己决定策略。',analogy:'TCP 像挂号快递：编号、确认、丢件重寄；UDP 像明信片：发出去很轻，但不替你保证。',why:'不同应用对“可靠、低延迟、开销”权衡不同，因此传输层提供不同基元。',mechanism:['TCP 建立逻辑连接并维护序号','接收方确认收到的数据','丢包触发重传并调整发送速率','UDP 只提供基本数据报，不维护连接可靠性'],aiUse:'HTTP/1.1、HTTP/2 通常建立在 TCP；实时音视频/游戏常需要更低延迟策略；QUIC 则在 UDP 上重新实现现代传输能力。',debug:'连接超时、reset、丢包、拥塞与应用 500 是不同层问题。先定位失败发生在哪一层。',terms:[['port','同一主机上区分网络应用的逻辑编号'],['connection','双方维护的一段传输会话状态'],['retransmission','检测到丢失后重新发送'],['congestion control','根据网络拥塞动态调整发送速度']],connects:['ip-routing','http-tls','backend-api','observability']},
  {id:'http-tls',domain:'network',title:'HTTP、TLS 与一次请求',en:'HTTP & TLS',depth:'应用层',summary:'HTTP 规定“客户端怎样描述请求、服务器怎样描述响应”；TLS 在其下方提供加密、完整性和服务器身份验证。',analogy:'HTTP 是信件格式；TLS 是防拆封的加密信封和可信证件。',why:'Web 需要通用的资源请求协议；当互联网承载账号、支付和私人数据后，又需要避免中间人偷看或篡改。',mechanism:['DNS 找到服务器地址','建立传输连接','TLS 握手协商密钥并验证证书','发送 HTTP method/path/headers/body','服务器处理后返回 status/headers/body'],aiUse:'调用 AI API、本地前后端通信、Webhook、REST、下载资源，本质上几乎都在重复这一请求/响应模型。',debug:'404 是资源/路由层，401/403 是身份权限，429 是限流，5xx 多半是服务器处理失败；TLS 错误则在 HTTP 之前。',terms:[['method','GET/POST 等请求意图'],['status code','服务器对请求结果的分类编号'],['header','请求/响应的元信息'],['TLS certificate','帮助客户端验证服务器身份的证书']],connects:['dns','tcp-udp','backend-api','auth-security']},
  {id:'data-structures',domain:'programming',title:'变量、类型与数据结构',en:'State & Data Structures',depth:'代码层',summary:'程序就是不断读取、改变状态。变量给状态起名字，类型约束“什么操作是合理的”，数据结构决定如何组织大量状态。',analogy:'变量是贴标签的盒子；数组/对象/Map 是不同形状的收纳系统。选错收纳方式，找东西就会越来越痛苦。',why:'没有结构的状态无法可靠修改；类型和数据结构把可能出错的空间缩小。',mechanism:['值存在内存中，变量保存或引用这些值','数组擅长按位置组织，Map 擅长按键查找','对象把相关字段组合成一个实体','不可变/可变选择会影响状态追踪与并发安全'],aiUse:'让 AI 写功能前，先让它说明“有哪些状态、各是什么类型、谁拥有它们”，能显著减少后续混乱。',debug:'很多 bug 是状态形状不一致：字段缺失、字符串/数字混用、null 未处理、多个副本不同步。',terms:[['variable','给一个值或引用起的名字'],['type','值允许哪些操作的一组约束/类别'],['array','按顺序组织元素的数据结构'],['object/map','按字段或键组织值的数据结构']],connects:['control-flow','functions-modules','data-model','frontend-state']},
  {id:'control-flow',domain:'programming',title:'条件、循环与状态机',en:'Control Flow & State Machines',depth:'代码层',summary:'条件决定“走哪条路”，循环决定“重复多少次”，状态机则把复杂流程明确成“当前在哪个状态、允许去哪里”。',analogy:'地铁闸机不是一堆 if，而是一台状态机：未刷卡→已验证→开门→通过→复位。',why:'真实软件不是线性脚本，而是根据输入、错误、时间和用户动作走不同路径。',mechanism:['if/else 按布尔条件分支','loop 对集合或条件重复执行','状态机把合法状态和转移显式列出','异步流程通常更适合用状态而不是堆叠回调理解'],aiUse:'登录流程、游戏下载/加载、订单、AI agent 工作流都非常适合先画状态机再让 AI 写代码。',debug:'出现“偶尔卡死/按钮失效/重复提交”时，先列出当前状态与允许事件，通常比盯代码更快。',terms:[['branch','根据条件选择执行路径'],['loop','重复执行一段逻辑'],['state machine','用有限状态和转移描述流程的模型'],['event','触发状态变化的输入或事件']],connects:['data-structures','functions-modules','frontend-state','rag-agents']},
  {id:'functions-modules',domain:'programming',title:'函数、模块与抽象边界',en:'Functions & Modules',depth:'代码层',summary:'函数把一段行为包装成“输入→输出/副作用”的单元；模块把相关函数与数据边界组织起来。',analogy:'餐厅后厨：菜单是接口，菜名告诉你能点什么，但不需要每位顾客都知道后厨如何切菜。',why:'软件规模变大后，唯一可持续的方法是隐藏不必要细节，让不同部分通过稳定接口协作。',mechanism:['函数接收参数并产生结果或副作用','模块只暴露外部需要的接口','调用方依赖契约，而不是内部实现','重构的目标常是改变内部而不破坏外部契约'],aiUse:'提示 AI “不要改接口，只重构内部”“把副作用隔离”比“帮我优化一下”更容易得到可控改动。',debug:'函数名与返回值说一套、实际行为另一套，或模块相互循环依赖，都是边界失控信号。',terms:[['function','可重复调用的行为单元'],['parameter','调用函数时传入的输入占位'],['return value','函数对调用者返回的结果'],['module','组织并封装相关代码的边界']],connects:['data-structures','runtime-errors','backend-api','deployment-ci']},
  {id:'runtime-errors',domain:'programming',title:'运行时、调用栈与错误',en:'Runtime, Stack & Errors',depth:'代码层',summary:'源代码要在某个运行时中执行。函数调用形成调用栈；异常把“哪里失败、从哪里调用过来”的链条暴露出来。',analogy:'调用栈像一摞“办完这件事后回到哪里”的便签。出错时 stack trace 就是沿便签倒查现场。',why:'机器只能执行底层指令，高级语言需要编译器/解释器/runtime 提供对象、内存管理、异常等能力。',mechanism:['入口函数开始执行','调用新函数时压入一层栈帧','返回时弹出栈帧','异常若未被处理就沿调用链向上传播','stack trace 记录关键调用位置'],aiUse:'AI 能解释报错，但你必须先提供完整错误信息、触发步骤和相关代码；最有价值的是 stack trace，而不是一句“它坏了”。',debug:'从第一条属于你代码的 stack frame 开始看；区分 syntax/build error、runtime exception、logic bug 和 external failure。',terms:[['runtime','承载程序实际执行的环境'],['call stack','记录嵌套函数调用关系的栈结构'],['exception','打断正常控制流的错误/异常对象'],['stack trace','异常发生时的调用路径记录']],connects:['functions-modules','process-thread','observability','backend-api']},
  {id:'data-model',domain:'data',title:'数据模型与 Schema',en:'Data Modeling',depth:'数据层',summary:'数据库最难的往往不是 SQL，而是决定“现实世界要切成哪些实体、字段和关系”。',analogy:'拍照前先决定地图图例：道路、建筑、河流该怎么表示；图例一旦乱，后面所有查询都会痛苦。',why:'现实是连续复杂的，软件必须选择有限字段表示它。Schema 把这些选择变成长期契约。',mechanism:['识别实体与唯一标识','拆出字段与数据类型','定义一对一/一对多/多对多关系','用约束保证不可能状态不要进入数据库'],aiUse:'做账号、存档、订单、内容系统前，让 AI 先产出实体关系图和约束，再写表结构。',debug:'如果一个字段同时表达多种含义、JSON 里重复大量同类信息、删除一条数据会破坏别处，通常是模型边界有问题。',terms:[['schema','数据结构与约束的正式定义'],['entity','要被系统长期表示的对象'],['primary key','唯一标识一条记录的键'],['relation','实体之间的关联关系']],connects:['sql','index-transaction','backend-api','frontend-state']},
  {id:'sql',domain:'data',title:'SQL 与关系代数直觉',en:'SQL',depth:'数据层',summary:'SQL 不是逐行告诉数据库“怎么循环”，而是声明“我想要满足什么条件的结果”，优化器再选择执行计划。',analogy:'你对图书管理员说“找 2025 年以后、作者是 X 的书”，而不是指挥他先走第几排再翻第几个抽屉。',why:'数据查询需要独立于物理存储方式；声明式语言让数据库能根据统计信息选择更好的执行策略。',mechanism:['FROM 确定数据来源','WHERE 过滤行','JOIN 按关系组合表','GROUP BY 聚合','优化器根据索引/统计信息选择扫描、连接顺序等计划'],aiUse:'AI 很会写“看起来像 SQL”的语句，但你仍要检查 join 条件、NULL、聚合口径和是否会扫描巨大表。',debug:'结果数量爆炸先查 JOIN；统计不对先查过滤口径和 NULL；慢查询看执行计划而不是只盯 SQL 字符串。',terms:[['SELECT','声明要返回哪些列/表达式'],['JOIN','按条件把多张表的行组合起来'],['NULL','缺失/未知值，不等于 0 或空字符串'],['query plan','数据库实际选择的查询执行策略']],connects:['data-model','index-transaction','backend-api']},
  {id:'index-transaction',domain:'data',title:'索引、事务与一致性',en:'Indexes & Transactions',depth:'数据层',summary:'索引用额外空间换查询速度；事务把一组读写包装成“要么整体成立、要么整体不成立”的一致性单元。',analogy:'索引像书末目录，不必从第一页找关键词；事务像银行转账，扣款和入账不能只成功一半。',why:'数据量大后全表扫描太慢；多人同时修改时又必须防止部分写入和并发冲突破坏规则。',mechanism:['索引维护键到记录位置的有序/哈希结构','查询可从索引缩小候选范围','每次写入也要维护索引，因此索引不是越多越好','事务通过日志、锁/MVCC 等机制提供原子性与隔离'],aiUse:'排行榜、搜索、用户表、订单表一旦变大，“为什么慢/为什么重复扣款”就会碰到索引和事务。',debug:'慢查询看是否命中合适索引；重复/脏数据看唯一约束和事务边界；死锁则看并发锁顺序。',terms:[['index','加速特定查询的辅助数据结构'],['transaction','作为整体提交或回滚的一组操作'],['ACID','常用来描述事务原子性、一致性、隔离性、持久性'],['MVCC','用多版本数据支持并发读写的一类机制']],connects:['sql','cache','backend-api','observability']},
  {id:'cache',domain:'data',title:'缓存与失效',en:'Caching',depth:'性能层',summary:'缓存把昂贵结果放到更快位置，核心难点不是“怎么存”，而是“什么时候它已经不可信”。',analogy:'你把常用资料贴在桌边很快，但原文件更新后，便利贴可能变成旧答案。',why:'网络、数据库、磁盘、计算都有成本；大量请求会重复访问相同内容，因此重用结果能大幅降低延迟与费用。',mechanism:['先查缓存是否命中','未命中再访问原始数据源','结果写入缓存并设置淘汰/过期策略','源数据变化时需要失效、更新或接受短暂旧值'],aiUse:'CDN、浏览器缓存、Redis、LLM prompt cache 都是同一类思想：用空间和一致性复杂度换速度/成本。',debug:'“我明明改了为什么页面还是旧的”优先怀疑缓存层；排查时明确每一层缓存键、TTL 和失效机制。',terms:[['cache hit','请求直接从缓存得到结果'],['cache miss','缓存中没有可用结果，需要访问后端'],['TTL','缓存条目的生存时间'],['invalidation','让旧缓存失效的过程']],connects:['memory','index-transaction','dns','observability']},
  {id:'browser-dom',domain:'web',title:'浏览器、HTML/CSS 与 DOM',en:'Browser & DOM',depth:'产品层',summary:'浏览器把 HTML 解析成 DOM，把 CSS 计算成样式与布局，再绘制像素；JavaScript 可以修改这棵结构并响应事件。',analogy:'HTML 是建筑结构，CSS 是装修规则，DOM 是浏览器实际建立出来、可被脚本操作的“现场模型”。',why:'Web 需要一种跨系统、可链接、可演进的文档与应用平台，因此浏览器承担了庞大的运行时角色。',mechanism:['HTML 解析为 DOM 树','CSS 规则匹配并计算样式','布局确定元素尺寸与位置','绘制/合成生成屏幕像素','JS 事件处理会改变 DOM/状态并触发后续更新'],aiUse:'AI 写前端时最常见的问题是只“看代码像对的”，却没理解布局、事件、状态和浏览器生命周期。',debug:'元素看不到先查 DOM 是否存在→CSS 是否隐藏/尺寸为 0→是否被覆盖→JS 是否报错。',terms:[['DOM','浏览器对文档结构建立的对象树'],['layout','计算元素尺寸和位置的阶段'],['paint','把视觉样式转换成绘制指令的阶段'],['event','点击、输入、网络完成等可触发代码的事件']],connects:['frontend-state','http-tls','runtime-errors','cache']},
  {id:'frontend-state',domain:'web',title:'前端状态与渲染',en:'Frontend State',depth:'产品层',summary:'界面不是一堆静态按钮，而是“状态 → UI”的投影。好的前端会让每份状态有清晰来源，避免多个副本互相打架。',analogy:'仪表盘不是自己决定数字，它只是把油量、速度等真实状态映射到表盘。',why:'交互应用会不断接受用户输入和网络结果；若 UI 更新靠到处手动改 DOM，很快就无法推理。',mechanism:['定义最小必要状态','事件触发状态变化','渲染函数根据新状态重新计算 UI','派生值尽量从源状态计算而不是重复保存'],aiUse:'React/Vue/Svelte 的大量概念最终都在解决状态所有权、更新与渲染一致性。',debug:'UI 不同步时先问：这份值谁拥有？是否有两个来源？更新是否异步？是否把可计算值重复存成状态？',terms:[['state','会随时间变化并影响界面的数据'],['render','根据当前状态生成界面的过程'],['component','封装一部分 UI 与行为的单元'],['derived state','可由其他状态计算得到的值']],connects:['browser-dom','data-structures','backend-api','auth-security']},
  {id:'backend-api',domain:'web',title:'后端、API 与请求生命周期',en:'Backend & APIs',depth:'产品层',summary:'后端接收请求、验证身份与输入、执行业务规则、读写数据，再返回结果。API 是前后端之间稳定的契约。',analogy:'餐厅前台收订单，后厨按规则处理并访问库存；菜单是 API 契约，顾客不直接闯进仓库。',why:'敏感数据、数据库凭证和核心规则不能依赖客户端自觉，因此需要可信服务器边界。',mechanism:['路由匹配 method + path','中间件做日志、身份、限流等通用处理','校验输入后执行业务逻辑','调用数据库/第三方服务','统一转换为 HTTP 响应与错误'],aiUse:'调用模型、隐藏 API Key、保存用户数据、支付、权限控制都应该落在后端可信边界。',debug:'抓住 request id，从入口日志沿数据库/第三方调用追踪；不要只在前端猜“后端坏了”。',terms:[['endpoint','API 中一个可调用的 method+path'],['validation','检查输入是否满足结构和业务约束'],['middleware','插入请求处理链的通用逻辑'],['idempotency','重复请求不会造成重复副作用的性质']],connects:['http-tls','data-model','auth-security','observability']},
  {id:'auth-security',domain:'web',title:'身份认证、授权与密钥',en:'Auth & Security',depth:'安全层',summary:'认证回答“你是谁”，授权回答“你能做什么”。安全不是一个登录页，而是贯穿每次请求、数据访问和密钥管理的边界。',analogy:'门卫先验身份证（认证），再看你的门禁级别（授权）。知道你是谁不代表你能进财务室。',why:'客户端和网络都可能被伪造；系统必须让关键决策在可信环境中重新验证。',mechanism:['登录后建立 session 或签发 token','每次敏感请求在后端解析身份','根据资源所有权/角色检查授权','秘密只保存在服务端或秘密管理系统','输入输出都按不可信数据处理'],aiUse:'API Key 永远不要放在公开前端；AI 输出也不能直接当 SQL、Shell、HTML 或工具调用执行。',debug:'401 看是否未认证/凭据无效；403 看已认证但无权限；越权漏洞常来自“只在 UI 隐藏按钮，后端没检查”。',terms:[['authentication','确认请求主体是谁'],['authorization','判断主体是否有权执行动作'],['session/token','维持已登录身份的机制'],['secret','必须限制访问的密钥/凭证']],connects:['permissions','http-tls','backend-api','rag-agents']},
  {id:'server-linux',domain:'cloud',title:'服务器、Linux 与进程环境',en:'Servers & Linux',depth:'运行层',summary:'“服务器”通常只是持续运行某个服务进程的远程计算环境。Linux 提供进程、文件、网络、用户等通用基础设施。',analogy:'不是一台神秘大铁箱，而是一间长期通电的工作室，里面有进程、文件、端口和权限规则。',why:'互联网服务需要稳定、自动化、可远程管理的运行环境；Linux 因开放、可组合、生态成熟而广泛使用。',mechanism:['服务作为进程启动','读取环境变量/配置','监听某个网络端口','由系统服务管理器/容器平台保持运行','日志写到标准输出或日志系统'],aiUse:'“本地能跑、部署不能跑”常常是环境变量、路径、端口、依赖、大小写或权限不同。',debug:'第一组问题永远是：进程启动了吗？监听哪里？配置是什么？日志最后一条错误是什么？',terms:[['environment variable','由运行环境注入的键值配置'],['daemon/service','长期后台运行并提供服务的进程'],['stdout/stderr','程序标准输出与错误输出流'],['PID','系统标识一个进程的编号']],connects:['process-thread','filesystem','permissions','container']},
  {id:'container',domain:'cloud',title:'容器与镜像',en:'Containers & Images',depth:'运行层',summary:'容器不是“小虚拟机”，而是利用操作系统隔离机制，把一组进程看到的文件、网络和资源边界切出来。镜像则描述其只读文件系统基础。',analogy:'同一栋楼里划出多个独立工作间：共享建筑基础设施，但每间看到自己的物品和门牌。',why:'“依赖版本、系统库、启动命令”在不同机器上不一致会导致部署漂移；容器把运行环境一起声明。',mechanism:['镜像由分层文件系统组成','启动容器时在镜像之上加可写层','namespace 隔离进程/网络等视图','cgroup 限制资源使用','数据持久化通常放到外部卷/数据库'],aiUse:'AI 能写 Dockerfile，但你需要理解 build-time 与 run-time、端口映射、环境变量、持久化，否则只能靠试错。',debug:'容器退出先看进程日志和 exit code；能在容器里访问但外部不能访问，查监听地址/端口映射/防火墙。',terms:[['image','用于创建容器的只读文件系统与配置模板'],['container','基于镜像启动、受隔离的一组进程'],['namespace','隔离进程所见系统资源的一类内核机制'],['cgroup','限制/统计进程资源使用的一类机制']],connects:['server-linux','permissions','deployment-ci','observability']},
  {id:'deployment-ci',domain:'cloud',title:'构建、部署与 CI/CD',en:'Build & Deployment',depth:'交付层',summary:'开发代码要经过依赖安装、构建、测试、配置、发布，才能成为用户真正访问的版本。CI/CD 把这些步骤机器化、可重复化。',analogy:'不是“把文件扔上去”，而是一条工厂流水线：原料→质检→包装→上架→可回滚批次。',why:'手工部署不可重复、难审计、容易漏步骤；自动化流水线能把版本、测试和发布绑定在一起。',mechanism:['提交代码产生版本','CI 在干净环境安装依赖并运行测试/构建','产物被发布到目标环境','健康检查确认新版本可服务','失败时阻止发布或回滚'],aiUse:'让 AI 修改代码时，Git diff + 自动测试 + 可回滚部署比“相信它一次写对”重要得多。',debug:'区分 build failure、deploy failure、runtime failure；每个阶段都需要不同日志和证据。',terms:[['build','把源代码转换成可运行/可发布产物'],['CI','持续集成：自动验证每次代码变更'],['CD','持续交付/部署：自动化发布流程'],['rollback','把线上版本退回已知稳定版本']],connects:['functions-modules','server-linux','container','observability']},
  {id:'observability',domain:'cloud',title:'日志、指标与可观测性',en:'Observability',depth:'可靠性层',summary:'当系统跨前端、后端、数据库和第三方服务后，“感觉它慢”不够。需要日志、指标、追踪把一次请求的证据串起来。',analogy:'医生不能只听“我不舒服”，还要体温、血压、化验和病史；系统排障也需要多种证据。',why:'分布式系统中的故障往往只在特定用户、版本或流量条件下出现，无法靠本地复现猜出来。',mechanism:['logs 记录离散事件与上下文','metrics 记录可聚合数值趋势','traces 记录请求跨服务的调用链','alert 根据阈值/异常触发响应','request/correlation id 把证据串起来'],aiUse:'把“错误日志 + 指标变化 + 触发条件”交给 AI，价值远高于一句“网站坏了”。',debug:'先建立时间线：什么时候开始、影响多少用户、哪个版本变化、错误集中在哪条调用链。',terms:[['log','带时间与上下文的事件记录'],['metric','可聚合的数值时间序列'],['trace','一次请求跨组件的调用路径'],['SLO','对服务可靠性目标的量化描述']],connects:['runtime-errors','backend-api','index-transaction','deployment-ci']},
  {id:'tokens-embeddings',domain:'ai',title:'Token、Embedding 与表示',en:'Tokens & Embeddings',depth:'模型层',summary:'大模型先把文本切成 token，再把 token 映射成高维向量。模型真正计算的是数字表示，而不是人类语义本身。',analogy:'先把句子拆成模型自己的“拼图块”，再把每块放进一个很多维的坐标空间，后续运算都在坐标上进行。',why:'神经网络需要固定形式的数字输入；tokenization 控制序列长度，embedding 把离散符号变成可学习的连续表示。',mechanism:['Tokenizer 把字符串转换成 token id','Embedding table 把 id 查成向量','位置/上下文信息与向量结合','模型层不断变换这些向量','输出层把最终表示映射回下一个 token 的概率'],aiUse:'上下文成本、截断、RAG chunk 大小、多语言 token 效率都与 tokenization 直接相关。',debug:'模型“忘了前文”先查上下文是否被截断；检索效果差则看 chunk、embedding 模型和相似度策略。',terms:[['token','模型处理文本的离散片段单位'],['tokenizer','文本与 token id 之间的转换规则'],['embedding','把离散对象映射到连续向量空间的表示'],['vector similarity','比较向量接近程度的方法']],connects:['bits-bytes','transformer','inference-training','rag-agents']},
  {id:'transformer',domain:'ai',title:'Transformer 与注意力',en:'Transformer & Attention',depth:'模型层',summary:'Transformer 的核心不是“数据库式查答案”，而是让每个位置根据当前表示，对上下文中的其他位置分配注意力并混合信息。',analogy:'写一句话时，每个词都在“回头看”上下文，但看的重点不同；attention 学习这些相关性权重。',why:'相比严格顺序处理序列的旧架构，Transformer 更容易并行训练，并能灵活建模长距离依赖。',mechanism:['输入向量产生 Query/Key/Value','Q 与 K 计算相关性分数','softmax 把分数转成权重','权重加权汇总 V 得到上下文信息','多头注意力并行学习不同关系，再经过前馈网络与残差层'],aiUse:'理解为什么提示词顺序、上下文噪声、长上下文和 KV Cache 会影响推理。',debug:'不要把“attention 能看上下文”误解为精确数据库检索；事实可靠性仍需要外部数据、验证和工具。',terms:[['attention','按相关性对上下文信息加权汇总的机制'],['Q/K/V','注意力中用于匹配与汇总的三组投影'],['softmax','把一组分数归一化成权重的函数'],['layer','模型中重复堆叠的一层计算模块']],connects:['tokens-embeddings','gpu','inference-training','rag-agents']},
  {id:'inference-training',domain:'ai',title:'训练、推理与概率生成',en:'Training & Inference',depth:'模型层',summary:'训练阶段用海量样本调整参数；推理阶段固定参数，给定上下文反复预测“下一个 token 的概率分布”并采样/选择。',analogy:'训练像长期练习改变大脑习惯；推理像考试时使用已经形成的能力，不会因为一次题目就重写全部大脑。',why:'把大量模式压缩进参数后，同一模型可以在新输入上快速泛化，而无需每次重新搜索全部训练数据。',mechanism:['训练：前向计算得到预测','损失函数度量预测与目标差异','反向传播计算参数梯度并更新','推理：参数固定，只做前向计算','每生成一个 token 都把新 token 加回上下文继续预测'],aiUse:'理解 temperature、延迟、吞吐、模型尺寸、微调、上下文长度时必须区分 training 与 inference。',debug:'输出不稳定不一定是“模型坏了”：检查 temperature、system prompt、上下文、模型版本、工具结果与随机采样。',terms:[['parameter','训练中被调整、推理时用于计算的模型数值'],['loss','衡量模型预测误差的目标函数'],['inference','用已训练模型对新输入进行计算'],['temperature','调整采样分布尖锐程度的参数']],connects:['gpu','transformer','tokens-embeddings','rag-agents']},
  {id:'rag-agents',domain:'ai',title:'RAG、工具调用与 Agent',en:'RAG & Agents',depth:'系统层',summary:'RAG 把外部资料检索进上下文；工具调用让模型请求程序执行确定动作；Agent 则把“观察→决定→调用工具→再观察”循环起来。',analogy:'模型像一个聪明但只能看桌面材料的员工：RAG 是资料员，工具调用是让他填写工单给专业系统，Agent 是允许他按步骤反复办事。',why:'模型参数无法实时包含你的私有数据，也不适合可靠执行数据库修改、发邮件、付款等确定操作。',mechanism:['RAG：切分文档→向量化→检索候选→把证据放入上下文','Tool calling：模型输出结构化工具意图→程序校验→执行→结果返回模型','Agent：重复上述过程直到达成目标或触发上限','安全边界必须由程序控制，而不是由模型自觉'],aiUse:'“让 AI 读我的资料”“查订单”“自动发邮件”“多步工作流”几乎都属于这一系统层，而不只是 prompt 技巧。',debug:'先分别验证检索质量、工具 schema、权限、重试与终止条件；不要把整个 agent 当一个黑盒一起调。',terms:[['RAG','检索增强生成：把外部检索结果注入模型上下文'],['tool calling','模型以结构化形式请求外部程序执行动作'],['agent loop','模型与工具多轮交互完成目标的循环'],['guardrail','限制/验证模型行为的程序化安全边界']],connects:['tokens-embeddings','transformer','auth-security','control-flow']}
];

export const goalPaths = [
  {id:'website',title:'做一个可上线的网站',icon:'◩',result:'从“一个页面”一路走到域名、后端与可观测性',nodes:['browser-dom','frontend-state','http-tls','backend-api','data-model','auth-security','deployment-ci','observability']},
  {id:'game',title:'做一个小游戏',icon:'◆',result:'理解状态、帧、资源与性能，再让 AI 帮你迭代系统',nodes:['data-structures','control-flow','functions-modules','runtime-errors','cpu','memory','filesystem','deployment-ci']},
  {id:'aiapp',title:'做一个 AI 产品',icon:'✦',result:'不只会调 API，还理解模型、上下文、RAG 与安全边界',nodes:['http-tls','backend-api','tokens-embeddings','transformer','inference-training','rag-agents','auth-security','observability']},
  {id:'automation',title:'做自动化工具',icon:'↻',result:'从脚本到可靠工作流，知道路径、权限、错误和 API 在哪里出问题',nodes:['filesystem','permissions','data-structures','functions-modules','runtime-errors','http-tls','backend-api','deployment-ci']},
  {id:'datawork',title:'做数据/运营工具',icon:'▥',result:'从数据模型到 SQL、索引、缓存与可观测指标',nodes:['data-model','sql','index-transaction','cache','backend-api','auth-security','deployment-ci','observability']}
];

export const resources = [
  {tag:'总览',title:'CS50x 2026',by:'Harvard',href:'https://cs50.harvard.edu/x/',note:'从计算思维、C、内存、Python、SQL 到 Web，适合补整张计算机地图。'},
  {tag:'硬件',title:'Nand2Tetris',by:'Nand2Tetris',href:'https://www.nand2tetris.org/',note:'从逻辑门一路搭到 CPU、机器语言、虚拟机与操作系统，真正理解“层是怎么叠起来的”。'},
  {tag:'系统',title:'Operating Systems: Three Easy Pieces',by:'UW–Madison',href:'https://pages.cs.wisc.edu/~remzi/OSTEP/',note:'免费在线书，围绕虚拟化、并发、持久化理解操作系统。'},
  {tag:'网络',title:"Beej's Guide to Network Programming",by:'Brian Hall',href:'https://beej.us/guide/bgnet/',note:'从 socket 编程进入 TCP/IP 的实作型网络教程。'},
  {tag:'Web',title:'MDN Learn Web Development',by:'Mozilla / MDN',href:'https://developer.mozilla.org/zh-CN/docs/Learn_web_development',note:'从浏览器、HTML/CSS/JS 到现代前端实践的结构化入门。'},
  {tag:'Git',title:'Pro Git 中文版',by:'git-scm.com',href:'https://git-scm.com/book/zh/v2',note:'理解版本、分支、提交，而不是只会复制 Git 命令。'},
  {tag:'SQL',title:'SQLBolt',by:'SQLBolt',href:'https://sqlbolt.com/',note:'边看边练 SQL，适合第一次建立关系数据库直觉。'},
  {tag:'部署',title:'Docker Get Started',by:'Docker Docs',href:'https://docs.docker.com/get-started/',note:'通过官方练习理解镜像、容器、构建与发布。'},
  {tag:'AI',title:'Hugging Face Learn',by:'Hugging Face',href:'https://huggingface.co/learn',note:'继续进入 Transformer、LLM 与开源 AI 工具链。'}
];