export type VisualKind = 'bits'|'cpu'|'memory'|'process'|'callstack'|'dns'|'http'|'index'|'browser'|'auth'|'embedding'|'llm';
export type GroupId = 'foundation'|'runtime'|'internet'|'product'|'ai';
export type KnowledgeNode = {
  id:string; group:GroupId; order:number; title:string; en:string; question:string; oneLine:string; analogy:string; why:string;
  mechanism:string[]; aiUse:string; debug:string[]; terms:[string,string][]; connects:string[]; visual:VisualKind;
  resource:{title:string; note:string; href:string};
};
export type Group = {id:GroupId; number:string; title:string; en:string; thesis:string};

export const groups:Group[] = [
  {id:'foundation',number:'01',title:'信息与机器',en:'Information & Machine',thesis:'先理解计算机到底在“存什么、算什么、为什么会慢”。'},
  {id:'runtime',number:'02',title:'程序如何运行',en:'Runtime & OS',thesis:'代码不是文字作品；它会变成进程、调用栈、内存和不断变化的状态。'},
  {id:'internet',number:'03',title:'互联网如何连接',en:'Internet',thesis:'一个网址能工作，是名字解析、传输、加密和应用协议共同完成的。'},
  {id:'product',number:'04',title:'产品、数据与身份',en:'Product & Data',thesis:'真正的软件产品需要界面、数据查找和身份边界一起正确工作。'},
  {id:'ai',number:'05',title:'AI 模型如何工作',en:'AI Models',thesis:'大模型仍然是数据表示、矩阵计算、概率预测和软件系统。'}
];

export const nodes:KnowledgeNode[] = [
  {id:'bits-bytes',group:'foundation',order:1,title:'比特、字节与编码',en:'Bits, Bytes & Encoding',question:'为什么文字、图片、声音最后都能存在硬盘里？',oneLine:'计算机保存的不是“文字”或“图片”，而是一串字节；格式与编码负责规定这些字节应该被怎样解释。',analogy:'像一串乐高积木。积木本身只是颜色与位置，说明书决定它最后被解释成汽车、房子还是机器人。',why:'数字电路最容易稳定区分两种状态，因此底层用 0/1。更高层再用 UTF-8、PNG、MP3 等规则，把比特组合解释成人类需要的信息。',mechanism:['bit 只有 0 或 1 两种状态；8 个 bit 通常组成 1 byte。','同一个 byte 序列可以被不同规则解释；解释规则不一致就会出现乱码或文件损坏。','文件扩展名只是提示，真正决定内容的是字节布局与格式规范。','网络传输、磁盘保存、模型输入最终都必须落回字节。'],aiUse:'理解文件上传、Base64、Token、上下文长度和“为什么一个模型不能直接理解任意文件”时，这一层是地基。',debug:['乱码：先检查发送端与读取端是否使用同一种字符编码。','文件打不开：检查字节是否被截断、格式是否与扩展名一致。','接口体积异常：先区分字符数量、字节数量与编码后的大小。'],terms:[['bit','只能表示 0 或 1 的最小二进制单位。'],['byte','通常由 8 个 bit 组成的数据单位。'],['UTF-8','把 Unicode 字符映射成字节的常用编码。'],['format','规定一组字节如何组织和解释的格式。']],connects:['cpu','memory','tokens-embeddings'],visual:'bits',resource:{title:'Nand2Tetris · Boolean Logic',note:'如果想继续追到“比特怎样真的变成电路”。',href:'https://www.nand2tetris.org/'}},
  {id:'cpu',group:'foundation',order:2,title:'CPU、指令与时钟',en:'CPU & Instructions',question:'一段 Python 或 JavaScript 最后到底是怎么“跑起来”的？',oneLine:'CPU 不理解“登录”“保存”“生成图片”；它只会不断取出简单机器指令，译码、执行、写回。',analogy:'像一个极快但动作词汇很少的工人：搬、加、减、比较、跳转。复杂软件只是海量简单动作的编排。',why:'把所有复杂任务拆成稳定的基本指令后，同一套硬件就能运行完全不同的软件。',mechanism:['Program Counter 指向下一条要执行的机器指令。','Fetch：CPU 从内存取出指令。','Decode：控制单元判断需要哪些数据、哪种运算。','Execute / Write back：执行单元计算结果并写回寄存器或内存，然后进入下一轮。'],aiUse:'AI 写出来的高级代码最终也要变成机器可执行操作。理解 CPU 能帮助你区分“算法做太多工作”和“程序其实在等网络/磁盘”。',debug:['CPU 长时间 100%：优先怀疑计算量、死循环或过多并行任务。','CPU 很低但程序仍慢：可能在等待网络、磁盘、锁或 GPU。','一次改动让耗时暴涨：先看是否让循环次数或数据规模发生数量级变化。'],terms:[['instruction','CPU 能直接执行的一条机器动作。'],['register','CPU 内部极快、容量很小的存储位置。'],['clock','驱动处理器状态推进的节拍。'],['ISA','软件和 CPU 之间约定的指令集合。']],connects:['bits-bytes','memory','process-thread','callstack'],visual:'cpu',resource:{title:'Nand2Tetris · Machine Language',note:'把高级软件一路追到机器指令，是最直观的课程之一。',href:'https://www.nand2tetris.org/'}},
  {id:'memory',group:'foundation',order:3,title:'内存、地址与缓存层级',en:'Memory & Cache Hierarchy',question:'为什么电脑“还有很多硬盘空间”，程序却会爆内存？',oneLine:'程序运行时需要的是快速工作空间，而不是单纯的长期存储空间；越靠近 CPU 的存储越快，也越小。',analogy:'寄存器像手里拿着的纸条，Cache 像桌面，RAM 像抽屉，SSD 像仓库。仓库很大，但每次取东西都更慢。',why:'CPU 的计算速度远快于大容量存储，所以系统用多级存储把“常用数据”逐层靠近 CPU。',mechanism:['程序通过地址定位数据，并不直接操作“某一颗物理内存芯片”。','CPU 会优先从寄存器和多级 Cache 找数据，找不到再访问 RAM。','RAM 不够时，操作系统可能把不活跃的数据换到磁盘，但速度会明显下降。','访问模式会影响缓存命中率，所以“同样数量的数据”也可能有完全不同的速度。'],aiUse:'浏览器标签页爆内存、Node/Python OOM、本地模型显存不足、长上下文推理变慢，本质都与工作集大小和存储层级有关。',debug:['占用持续上涨不回落：检查对象是否被意外长期引用。','显存不足：检查模型大小、量化、上下文长度和 batch。','程序频繁卡顿且磁盘忙：可能发生大量换页。'],terms:[['address','程序用来定位数据的位置编号。'],['cache','保存近期/附近数据的高速小容量存储。'],['RAM','程序运行时主要使用的易失性工作内存。'],['OOM','Out Of Memory，无法再分配所需内存。']],connects:['cpu','process-thread','callstack','llm-generation'],visual:'memory',resource:{title:'CS50 · Memory',note:'用 C 和指针直观看到地址与内存。',href:'https://cs50.harvard.edu/x/'}},
  {id:'process-thread',group:'runtime',order:4,title:'进程、线程与调度',en:'Processes, Threads & Scheduling',question:'为什么一个程序卡住，不一定会把整台电脑一起卡死？',oneLine:'操作系统把运行中的程序隔离成进程，再把 CPU 时间分给不同线程，于是有限硬件看起来能同时做很多事。',analogy:'进程像独立办公室，线程像办公室里的员工。不同办公室互相隔离，同一办公室里的员工会共享很多资源。',why:'多个程序需要同时使用 CPU、内存和文件，但又不能互相随意破坏，因此操作系统必须提供隔离与调度。',mechanism:['启动程序后，OS 为它创建进程和独立的虚拟地址空间。','进程内可以有多个线程，共享大部分进程资源。','调度器让可运行线程轮流获得 CPU 时间片。','线程切换需要保存与恢复执行状态，因此并发并不是免费的。'],aiUse:'后端并发、游戏主线程、浏览器 Worker、批量 AI 请求都会遇到“并发是否真的有帮助”的问题。',debug:['界面冻结但后台还在跑：检查是否把耗时任务放在 UI 主线程。','线程越多反而越慢：检查上下文切换、锁竞争和共享资源。','某个进程崩溃：先区分是程序异常退出还是整个系统资源耗尽。'],terms:[['process','拥有独立资源边界的运行中程序实例。'],['thread','进程内部的一条执行流。'],['scheduler','决定哪个线程何时获得 CPU 的系统组件。'],['context switch','CPU 从一个执行流切换到另一个时保存/恢复状态。']],connects:['cpu','memory','callstack','http'],visual:'process',resource:{title:'OSTEP · Processes',note:'免费教材，适合继续理解进程、调度和虚拟化。',href:'https://pages.cs.wisc.edu/~remzi/OSTEP/'}},
  {id:'callstack',group:'runtime',order:5,title:'函数、调用栈与错误',en:'Functions, Call Stack & Errors',question:'报错里的那一串 stack trace 到底在告诉我什么？',oneLine:'函数调用会形成一层层“我从哪里来、局部变量是什么、执行完回哪里”的栈帧；错误栈就是这条调用路径。',analogy:'像进入一栋楼：main 进入 loadUser，loadUser 又进入 fetchProfile。出问题时，你沿着原路一层层退回去。',why:'程序需要记住嵌套函数执行到哪里、各自的局部状态是什么，调用栈提供了简单而高效的结构。',mechanism:['调用函数时创建新的 stack frame。','frame 保存参数、局部变量和返回位置等执行上下文。','函数返回时，顶部 frame 被弹出，执行回到调用者。','异常发生时，runtime 会沿调用链生成 stack trace，显示错误经过了哪些函数。'],aiUse:'AI 很擅长猜修复，但你把完整 stack trace、输入和触发步骤给它，定位准确率会高很多。',debug:['优先读第一条真正来自你代码的 stack frame，而不是最上面的框架内部调用。','递归无限增长会导致 stack overflow。','异步任务的调用链可能被事件循环切断，需要同时看日志与请求上下文。'],terms:[['stack frame','一次函数调用对应的一层执行记录。'],['stack trace','异常发生时的函数调用路径。'],['runtime','真正执行程序并提供运行期机制的环境。'],['exception','程序执行期间出现的异常事件。']],connects:['process-thread','memory','http','browser-dom'],visual:'callstack',resource:{title:'MDN · JavaScript execution model',note:'想理解调用栈、任务队列和事件循环时继续看。',href:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop'}},
  {id:'dns',group:'internet',order:6,title:'DNS：域名怎样找到服务器',en:'DNS',question:'为什么换了服务器，用户仍然可以继续输入同一个域名？',oneLine:'DNS 是互联网的名字系统：它把人类可读的域名逐级解析成程序能用于连接的网络地址。',analogy:'像查一个分层电话簿：先问“谁负责 .com”，再问“谁负责 example.com”，最后得到真正的地址。',why:'IP 地址会变化，也不适合人类记忆。把“名字”和“机器地址”解耦后，服务可以迁移而不改变用户入口。',mechanism:['浏览器/系统先检查本地缓存。','没有缓存时，请递归解析器代为查询。','解析器从根服务器、顶级域服务器一路找到权威 DNS。','权威服务器返回记录，结果会按 TTL 暂时缓存。'],aiUse:'部署 AI 网站、更换托管平台、配置自定义域名时，很多“网站打不开”其实是 DNS 记录或缓存问题，不是代码问题。',debug:['刚改 DNS 仍旧访问旧地址：检查 TTL 和本地/运营商缓存。','只有某些地区打不开：检查不同解析器得到的记录是否一致。','域名能解析但服务打不开：问题已经从 DNS 进入网络/服务器层。'],terms:[['A record','把域名映射到 IPv4 地址的记录。'],['CNAME','把一个名字指向另一个域名。'],['resolver','替客户端执行 DNS 查询的解析器。'],['TTL','DNS 记录允许被缓存的时间。']],connects:['http','auth-secrets'],visual:'dns',resource:{title:'Cloudflare Learning · DNS',note:'用图解继续理解递归解析与 DNS 记录。',href:'https://www.cloudflare.com/learning/dns/what-is-dns/'}},
  {id:'http',group:'internet',order:7,title:'HTTP、TLS 与一次请求',en:'HTTP & TLS',question:'你点击“登录”以后，到底有多少层东西在一起工作？',oneLine:'HTTP 负责描述“我想要什么/我返回什么”，TLS 负责加密与验证身份，底层传输协议负责把数据送到对端。',analogy:'像寄一份密封文件：DNS 找地址，传输层负责送到，TLS 是密封和验身份，HTTP 是文件正文的格式。',why:'网络层只负责把数据送到另一台机器，却不知道这是网页、JSON 还是图片；HTTP 提供统一的应用层表达，TLS 再提供机密性与身份验证。',mechanism:['先通过 DNS 得到服务地址。','建立传输连接，并通过 TLS 握手验证证书、协商密钥。','客户端发送 method、path、headers 和可选 body。','服务器经过路由、权限、业务逻辑和数据访问后生成 response。','浏览器/客户端根据 status、headers 和 body 更新自己的状态。'],aiUse:'调用模型 API、Web 前后端通信、Webhook、上传文件都建立在请求/响应模型上。',debug:['4xx 通常先检查请求、身份与权限；5xx 先检查服务端日志。','浏览器能打开但 API 失败：检查路径、method、CORS、cookie/header。','请求一直 pending：区分 DNS、连接、TLS、服务器处理或下载阶段。'],terms:[['request','客户端发给服务器的一次应用层请求。'],['response','服务器对请求返回的结果。'],['status code','服务器对请求结果的标准化状态编号。'],['TLS','为网络通信提供加密和身份验证的协议。']],connects:['dns','process-thread','browser-dom','auth-secrets','database-index'],visual:'http',resource:{title:'MDN · HTTP overview',note:'从请求方法、头、状态码继续深入。',href:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'}},
  {id:'database-index',group:'product',order:8,title:'数据库索引与查询',en:'Database Indexes',question:'为什么数据只有几百条时飞快，上百万条后同一个查询突然变慢？',oneLine:'索引是数据库为“更快找到记录”维护的额外数据结构；它用更多空间和写入成本换取查询速度。',analogy:'没有目录的书只能一页页翻；索引像按关键字排序的目录，让你先缩小范围再定位正文。',why:'如果每次查询都扫描整张表，成本会随数据量线性增长。索引让数据库能更快缩小候选范围。',mechanism:['SQL 描述你想要的结果，不直接规定数据库应该怎样找。','查询优化器根据统计信息选择全表扫描或索引等执行计划。','B-Tree 等索引把键组织成可快速缩小范围的结构。','索引不是越多越好：插入、更新、删除都要同步维护索引。'],aiUse:'AI 很容易给数据库“补一个索引”的建议，但你仍要判断查询模式、数据规模和写入代价。',debug:['慢查询先看执行计划，不要凭感觉改 SQL。','新增索引后写入变慢：检查是否维护了太多重复索引。','查询结果少但仍扫描很多行：检查过滤字段是否适合索引。'],terms:[['index','为快速定位数据维护的辅助结构。'],['query plan','数据库选择的实际查询执行方案。'],['B-Tree','常见的有序树形索引结构。'],['full table scan','逐行检查整张表的执行方式。']],connects:['http','auth-secrets','browser-dom'],visual:'index',resource:{title:'PostgreSQL · Indexes',note:'官方文档，适合继续理解索引类型与执行计划。',href:'https://www.postgresql.org/docs/current/indexes.html'}},
  {id:'browser-dom',group:'product',order:9,title:'浏览器、DOM 与渲染',en:'Browser Rendering',question:'HTML、CSS、JavaScript 为什么最后能变成屏幕上的按钮？',oneLine:'浏览器会把 HTML 解析成 DOM，把样式变成可计算规则，再经过布局与绘制生成像素；JavaScript 可以不断改变这棵界面树。',analogy:'HTML 是建筑结构，CSS 是装修规则，DOM 是浏览器正在维护的“现场模型”，渲染流程把模型真正画到屏幕上。',why:'Web 需要一种跨操作系统的文档与应用运行环境；浏览器承担了解析、布局、绘制、脚本执行和安全边界。',mechanism:['HTML 被解析成 DOM 树。','CSS 被解析并与 DOM 计算出元素最终样式。','Layout 计算每个元素的位置与尺寸。','Paint/Composite 把结果绘制成像素与图层。','JavaScript 修改状态或 DOM 后，相关阶段可能重新执行。'],aiUse:'AI 写前端时最常见的问题不是语法，而是“状态变了但 DOM 没按预期更新”“布局被 CSS 规则互相影响”。',debug:['元素存在但看不到：查 CSS、尺寸、层叠与布局。','点击没反应：查事件是否绑定、是否被覆盖、状态是否更新。','页面卡顿：检查是否频繁触发大范围渲染或执行耗时 JS。'],terms:[['DOM','浏览器对文档结构维护的对象树。'],['layout','计算元素几何位置和尺寸的阶段。'],['paint','把元素视觉效果绘制出来的阶段。'],['event','浏览器向脚本报告点击、输入等交互的机制。']],connects:['http','callstack','auth-secrets'],visual:'browser',resource:{title:'MDN · How browsers work',note:'继续理解解析、布局、绘制与事件。',href:'https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/How_browsers_work'}},
  {id:'auth-secrets',group:'product',order:10,title:'认证、授权与密钥',en:'Authentication, Authorization & Secrets',question:'为什么 API Key 不能直接写进前端代码？',oneLine:'认证回答“你是谁”，授权回答“你能做什么”；真正的秘密必须放在用户拿不到的可信边界里。',analogy:'认证像出示身份证，授权像门禁卡决定你能进哪些房间。把服务器密钥写进前端，相当于把总钥匙贴在大厅墙上。',why:'一旦软件连接真实用户与真实资源，就必须建立身份与权限边界，否则任何拿到请求格式的人都可能越权操作。',mechanism:['用户通过密码、OAuth 等方式证明身份。','服务器创建 session 或签发 token，把后续请求关联到该身份。','每次敏感操作还要再次做授权判断，而不是只看“已登录”。','服务器密钥保存在后端环境；浏览器只获得完成当前交互所需的最小信息。'],aiUse:'接模型 API、支付、数据库管理接口时，最常见的低级安全事故就是把服务端密钥暴露在浏览器。',debug:['401：通常是没有有效身份；403：通常是身份有效但没有权限。','用户 A 能看到用户 B 数据：优先检查后端授权条件，而不是前端隐藏按钮。','密钥已经提交到公开仓库：立即撤销/轮换，不要只删除文件。'],terms:[['authentication','确认请求者身份的过程。'],['authorization','决定某身份是否允许执行某操作。'],['session','服务器保存或识别的一段登录状态。'],['secret','只应存在于可信环境中的敏感凭据。']],connects:['http','database-index','browser-dom'],visual:'auth',resource:{title:'OWASP · Authentication Cheat Sheet',note:'进一步学习 Web 身份与安全边界。',href:'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html'}},
  {id:'tokens-embeddings',group:'ai',order:11,title:'Token、Embedding 与表示',en:'Tokens & Embeddings',question:'模型为什么不是直接“读懂一句中文”？',oneLine:'大模型先把文本切成 token，再把 token 映射成向量；后续计算操作的是数字表示，而不是人类看到的字词。',analogy:'token 像把句子切成模型自己的拼图块；embedding 像给每块拼图一个高维坐标，使模型能计算它们在上下文中的关系。',why:'神经网络需要连续数值输入，文本本身不是可直接做矩阵运算的对象，因此必须先离散化，再转成可学习的向量表示。',mechanism:['Tokenizer 按模型词表把字符串切成 token id。','Embedding table 把每个 id 映射成向量。','位置与上下文信息会在模型层中不断混合进表示。','相同单词在不同上下文里最终产生的内部表示也会不同。'],aiUse:'上下文长度、计费、截断、Embedding 搜索、RAG 都直接依赖 token 或向量表示。',debug:['提示词看起来不长却耗 token 多：检查语言、代码、JSON 和重复上下文。','向量检索结果离谱：检查切块策略、Embedding 模型和查询表达。','不要把“二维相似图”误认为模型真实内部空间；它只是教学投影。'],terms:[['token','模型处理文本时使用的离散片段。'],['tokenizer','把文本转换为 token id 的组件。'],['embedding','把离散项映射成连续向量的表示。'],['vector','由一串数字组成、可用于数学运算的表示。']],connects:['bits-bytes','llm-generation'],visual:'embedding',resource:{title:'Hugging Face · Tokenizers',note:'想看到真实 tokenizer 行为时继续实验。',href:'https://huggingface.co/docs/transformers/main/tokenizer_summary'}},
  {id:'llm-generation',group:'ai',order:12,title:'大模型怎样逐 Token 生成',en:'LLM Generation',question:'为什么模型会“一个字一个字”地输出，而且同一问题每次可能不一样？',oneLine:'生成式大模型反复计算“下一个 token 的概率分布”，选出一个 token 加回上下文，再继续预测下一个。',analogy:'像不断玩“下一词填空”：每一步都根据目前已经出现的全部上下文重新判断最可能的候选。',why:'语言建模把复杂的文本生成任务转成统一目标：给定前文，预测下一个 token。规模扩大后，这个目标能学习出大量语言与世界模式。',mechanism:['输入 token 先变成向量表示。','Transformer 层通过注意力与前馈网络混合上下文信息。','最后得到整个词表上“下一个 token”的 logits。','采样策略把 logits 转成具体选择；temperature 等参数改变随机性。','新 token 被追加到上下文，循环重复直到停止。'],aiUse:'理解温度、上下文、幻觉、流式输出、KV Cache、推理成本和为什么“让模型先规划再生成”会改变结果。',debug:['输出随机性过高：检查 temperature、top-p 等采样参数。','模型忘记早期信息：检查上下文是否被截断或被大量无关内容稀释。','成本/延迟异常：检查输入 token、输出 token、模型大小和并发。'],terms:[['logits','模型对每个候选 token 给出的未归一化分数。'],['sampling','从候选概率分布中选择下一个 token 的过程。'],['temperature','调节分布尖锐程度与随机性的参数。'],['context window','一次推理中模型可处理的 token 范围。']],connects:['tokens-embeddings','memory','http'],visual:'llm',resource:{title:'Hugging Face Course · Transformer models',note:'继续理解 Transformer、注意力和生成过程。',href:'https://huggingface.co/learn/llm-course/chapter1/4'}},
];

export const recommendedOrder = nodes.map(n=>n.id);
export const nodeById = new Map(nodes.map(n=>[n.id,n]));
export const groupById = new Map(groups.map(g=>[g.id,g]));