import { useMemo, useState } from 'react';
import type { VisualKind } from './knowledge';

function BitsVisual(){const [value,setValue]=useState(73);const weights=[128,64,32,16,8,4,2,1];const bits=value.toString(2).padStart(8,'0').split('');return <div className='vizBody'><div className='vizToolbar'><label>拖动十进制数值 <strong>{value}</strong><input aria-label='调整十进制数值' type='range' min='0' max='255' value={value} onChange={e=>setValue(Number(e.target.value))}/></label></div><div className='bitGrid'>{bits.map((bit,i)=><div className={`bitCell ${bit==='1'?'on':''}`} key={i}><span>{bit}</span><small>{weights[i]}</small></div>)}</div><div className='vizResult'>{bits.map((b,i)=>b==='1'?weights[i]:0).filter(Boolean).join(' + ')||'0'} = <b>{value}</b></div><p className='vizCaption'>每一格下面是这一位代表的权重。亮起的位相加，就得到当前数字。</p></div>}

const cpuSteps=[['取指 Fetch','PC 指向下一条机器指令，CPU 从内存把它取出来。'],['译码 Decode','控制单元判断这条指令需要什么数据、要做什么动作。'],['执行 Execute','ALU 或其他执行单元完成加法、比较、跳转等操作。'],['写回 Write back','结果进入寄存器或内存，PC 更新，下一轮继续。']];
function CpuVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='cpuFlow'>{['内存','指令寄存器','控制单元','执行单元'].map((x,i)=><div className={`vizNode ${i===step?'active':''}`} key={x}><span>0{i+1}</span><b>{x}</b><small>{['10110010','ADD R1,R2','选择 ALU','结果 → R1'][i]}</small></div>)}</div><div className='stepPanel'><div><small>第 {step+1}/4 步</small><h3>{cpuSteps[step][0]}</h3><p>{cpuSteps[step][1]}</p></div><button onClick={()=>setStep((step+1)%4)}>下一步 →</button></div></div>}

const memoryLayers=[['寄存器','CPU 手边','极小 · 极快'],['L1/L2/L3 Cache','CPU 附近','小 · 很快'],['RAM','程序工作区','较大 · 快'],['SSD','长期存储','很大 · 较慢']];
function MemoryVisual(){const [active,setActive]=useState(2);return <div className='vizBody'><div className='memoryPyramid'>{memoryLayers.map((x,i)=><button key={x[0]} className={i===active?'active':''} onClick={()=>setActive(i)} style={{width:`${56+i*13}%`}}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></button>)}</div><div className='vizCallout'><b>{memoryLayers[active][0]}</b><p>{active<2?'离 CPU 越近，取数据越快，但容量越有限。':active===2?'大多数正在运行的程序把主要工作集放在这里。':'适合长期保存；不能把“硬盘还有空间”当成“运行内存还够”。'}</p></div></div>}

function ProcessVisual(){const jobs=['界面线程','网络任务','音频任务'];const [tick,setTick]=useState(0);return <div className='vizBody'><div className='scheduler'><div className='cpuCore'><small>CPU CORE</small><strong>{jobs[tick%jobs.length]}</strong><span>正在获得时间片</span></div><div className='queue'>{jobs.map((j,i)=><div className={(tick%jobs.length)===i?'running':''} key={j}><b>{j}</b><small>{(tick%jobs.length)===i?'RUNNING':'READY'}</small></div>)}</div></div><button className='vizAction' onClick={()=>setTick(tick+1)}>让调度器切换一次 →</button><p className='vizCaption'>示意图：单个核心通过快速切换，让多个任务“看起来同时运行”。真实系统通常有多个核心与更复杂的调度策略。</p></div>}

function CallstackVisual(){const frames=[['main()','程序入口'],['loadUser()','准备用户页面'],['fetchProfile()','发起资料请求'],['parseJSON()','解析返回数据']];const [depth,setDepth]=useState(1);return <div className='vizBody'><div className='stackViz'>{frames.slice(0,depth).reverse().map((f,i)=><div className={`stackFrame ${i===0?'top':''}`} key={f[0]}><b>{f[0]}</b><span>{f[1]}</span><small>{i===0?'← 当前执行':'等待返回'}</small></div>)}</div><div className='dualActions'><button disabled={depth>=frames.length} onClick={()=>setDepth(Math.min(frames.length,depth+1))}>调用下一层</button><button disabled={depth<=1} onClick={()=>setDepth(Math.max(1,depth-1))}>函数返回</button></div><p className='vizCaption'>报错时的 stack trace，就是把这些层按调用路径列出来，帮助你从“出错点”追到“谁调用了它”。</p></div>}

const dnsSteps=[['浏览器缓存','先看最近是否查过这个域名'],['递归解析器','本机把查询交给 DNS resolver'],['Root / TLD','逐级找到谁负责 .com 与目标域名'],['权威 DNS','返回真正的 A / CNAME 等记录'],['得到地址','客户端终于知道该连接哪里']];
function DnsVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='routeViz'>{dnsSteps.map((s,i)=><button key={s[0]} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><span>{i+1}</span><b>{s[0]}</b></button>)}</div><div className='vizCallout'><b>{dnsSteps[step][0]}</b><p>{dnsSteps[step][1]}</p></div><button className='vizAction' onClick={()=>setStep((step+1)%dnsSteps.length)}>下一跳 →</button></div>}

const httpSteps=[['DNS','把域名变成地址'],['连接','建立 TCP/QUIC 传输通道'],['TLS','验证证书并建立加密'],['Request','发送 method、path、headers、body'],['Backend','路由 → 权限 → 业务 → 数据'],['Response','状态码 + headers + body'],['UI','客户端用结果更新界面']];
function HttpVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='httpRail'>{httpSteps.map((s,i)=><button key={s[0]} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><span>{i+1}</span><b>{s[0]}</b></button>)}</div><div className='packetLine'><span style={{width:`${step/(httpSteps.length-1)*100}%`}}></span></div><div className='vizCallout'><b>{httpSteps[step][0]}</b><p>{httpSteps[step][1]}</p></div><button className='vizAction' onClick={()=>setStep((step+1)%httpSteps.length)}>继续请求 →</button></div>}

function IndexVisual(){const [indexed,setIndexed]=useState(false);const rows=[12,18,24,31,37,42,48,53,59,64,70,73,79,85,91,97];const target=73;const checked=useMemo(()=>indexed?[64,85,73]:rows.slice(0,rows.indexOf(target)+1),[indexed]);return <div className='vizBody'><div className='indexHeader'><code>WHERE user_id = 73</code><label><input type='checkbox' checked={indexed} onChange={e=>setIndexed(e.target.checked)}/> 使用索引</label></div><div className='dbGrid'>{rows.map(v=><span className={v===target?'target':checked.includes(v)?'checked':''} key={v}>{v}</span>)}</div><div className='vizCallout'><b>{indexed?'索引：先缩小范围，再定位':'无索引：从头逐行检查'}</b><p>{indexed?'示意中只检查少量候选；真实数据库会根据索引结构和统计信息选择执行计划。':'目标在第 12 行，所以前 12 条都被检查。数据越大，这种方式越昂贵。'}</p></div></div>}

const renderSteps=[['HTML','解析为 DOM 树'],['CSS','计算样式规则'],['Layout','算位置与尺寸'],['Paint','绘制像素与图层'],['JS state','交互后改变状态，再触发必要更新']];
function BrowserVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='browserMock'><div className='browserBar'><i></i><i></i><i></i><span>example.app</span></div><div className={`browserCanvas phase-${step}`}><div className='mockCard'><small>{renderSteps[step][0]}</small><b>{step<2?'按钮':'Hello, AI Builder'}</b><span>{step===0?'结构已经存在':step===1?'样式开始生效':step===2?'位置尺寸确定':step===3?'像素被绘制':'状态变化 → 再渲染'}</span></div></div></div><div className='stepDots'>{renderSteps.map((s,i)=><button className={i===step?'active':''} onClick={()=>setStep(i)} key={s[0]}>{i+1}. {s[0]}</button>)}</div><div className='vizCallout'><b>{renderSteps[step][0]}</b><p>{renderSteps[step][1]}</p></div></div>}

const authSteps=[['登录','用户证明身份'],['Session','服务器建立身份状态'],['Request','浏览器携带 session/cookie'],['Authorize','后端判断这个人能否做这件事'],['Data','只返回被允许访问的数据']];
function AuthVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='authScene'><div className='authActor'>浏览器<small>{step>=2?'✓ 携带会话':'用户侧'}</small></div><div className='authArrow'>→</div><div className='authServer'>后端<small>{step>=3?'✓ 权限判断':'可信边界'}</small><div className='secretBadge'>API SECRET<br/><b>只在这里</b></div></div></div><div className='routeViz compact'>{authSteps.map((s,i)=><button key={s[0]} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><span>{i+1}</span><b>{s[0]}</b></button>)}</div><div className='vizCallout'><b>{authSteps[step][0]}</b><p>{authSteps[step][1]}</p></div></div>}

function EmbeddingVisual(){const [term,setTerm]=useState('猫');const points=[{n:'猫',x:25,y:28},{n:'狗',x:38,y:34},{n:'老虎',x:31,y:18},{n:'汽车',x:76,y:68},{n:'公交车',x:68,y:61},{n:'香蕉',x:52,y:80}];return <div className='vizBody'><div className='embeddingControls'><span>点击一个概念：</span>{points.map(p=><button className={term===p.n?'active':''} key={p.n} onClick={()=>setTerm(p.n)}>{p.n}</button>)}</div><div className='embeddingMap'>{points.map(p=><button aria-label={p.n} className={term===p.n?'active':''} style={{left:`${p.x}%`,top:`${p.y}%`}} onClick={()=>setTerm(p.n)} key={p.n}><i></i>{p.n}</button>)}</div><p className='vizCaption'>概念示意，不是任何真实模型的二维坐标。重点是：向量让“相似度”可以被计算；真实 embedding 通常有数百到数千维。</p></div>}

const llmSteps=[['Tokenize','文字切成 token id'],['Embed','token 变成向量'],['Attention','混合上下文信息'],['Logits','给所有候选 token 打分'],['Sample','按采样策略选一个'],['Loop','把新 token 放回上下文继续']];
function LlmVisual(){const [step,setStep]=useState(0);return <div className='vizBody'><div className='llmPipe'>{llmSteps.map((s,i)=><button className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)} key={s[0]}><span>{i+1}</span><b>{s[0]}</b></button>)}</div><div className='llmCanvas'><div className='promptChip'>“解释 HTTP”</div><span>→</span><div className='matrix'>{Array.from({length:18}).map((_,i)=><i key={i} style={{opacity:.18+((i+step*2)%7)/9}}></i>)}</div><span>→</span><div className='tokenChoice'>{step<4?'…':'“HTTP”'}<small>{step===4?'被选中':'候选'}</small></div></div><div className='vizCallout'><b>{llmSteps[step][0]}</b><p>{llmSteps[step][1]}</p></div><button className='vizAction' onClick={()=>setStep((step+1)%llmSteps.length)}>下一步 →</button></div>}

export default function VisualExplainer({kind}:{kind:VisualKind}){return <section className='visualShell'><div className='visualLabel'><span>INTERACTIVE MODEL</span><b>动手理解，而不是只读定义</b></div>{kind==='bits'?<BitsVisual/>:kind==='cpu'?<CpuVisual/>:kind==='memory'?<MemoryVisual/>:kind==='process'?<ProcessVisual/>:kind==='callstack'?<CallstackVisual/>:kind==='dns'?<DnsVisual/>:kind==='http'?<HttpVisual/>:kind==='index'?<IndexVisual/>:kind==='browser'?<BrowserVisual/>:kind==='auth'?<AuthVisual/>:kind==='embedding'?<EmbeddingVisual/>:<LlmVisual/>}</section>}